# Generated by Django 4.2.6 on 2023-11-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_thestore_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
        migrations.RenameModel(
            old_name='order_items',
            new_name='order_item',
        ),
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
