# Generated by Django 4.2.6 on 2023-11-18 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_supplier_is_active_alter_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='product_s',
        ),
    ]
