# Generated by Django 4.2.6 on 2023-11-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_order_customer_id_order_product_id_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_s',
            old_name='product_id',
            new_name='product_id_id',
        ),
    ]
