# Generated by Django 4.2.6 on 2023-11-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='product',
            new_name='product_id',
        ),
    ]
